create table diary(
num bigint generated by default as identity,
id varchar(20),
text varchar(1500),
target varchar(50),
date varchar(100),
weight double,
cardio double,
primary key(num),
foreign key(id) references registry(id));




create table record(
num bigint generated by default as identity
,
id varchar(20),
name varchar(50),
date varchar(100),
gender varchar(6),
rmr double,
height double,
weight double,
age int,
Primary key(num),
foreign key(id) references registry(id));


create table registry(
id varchar(20),
pw varchar(20),
primary key(id));
